apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-bghj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-bghj
    app.kubernetes.io/part-of: tkrw-pr714-0075-0047-app
  name: devfile-sample-bghj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-bghj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-bghj
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0047-tenant/tkrw-pr714-0075-0047-app/devfile-sample-bghj@sha256:334295a25c9a5a224fbdba68cc7b78b3164b7838024a8b3b219a0b8e22863e08
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
